### ISSUE TITLE
Add my website

### ISSUE THREAD

**Issue by King212pro** [Bon-Appetit/porn-domains#10]
**-- LINK REMOVED --**

**Comment by CodeAlDente** [comment]
> Adding individual domains is no longer supported. Instead please submit a GitHub-Repository **pointing to a list of domains**.

https://github.com/Bon-Appetit/porn-domains#somethings-missing

Also please don't use issue tickets to promote your website. Thank you.

**Comment by King212pro** [comment]
It is not mine, its a website than i found from the dark web. How i add
this to your list?

Il Sab 11 Dic 2021, 21:39 Code al Dente ***@***.***> ha
scritto:

**Comment by CodeAlDente** [comment]
If you want to add a domain please provide a GitHub-Repository pointing to a file that contains a list of domains. It works best if domains are listed line-by-line.
Take a look at the current [sources.json](https://github.com/Bon-Appetit/porn-domains/blob/master/sources.json) and make your change somewhere there by filing an issue ticket in that certain repository **-OR-** create your own repository and provide it as follows.
Submit the source either in an issue ticket with the format [described here](https://github.com/Bon-Appetit/porn-domains#somethings-missing) **-OR-** fork this repository and add the mentioned structure to your `sources.json` and send a pull request.
That way the sources can be downloaded and updated in background with the workflow I'm using on my local machine. After that I update this repository and can start a DNS check additionally.
