### ISSUE TITLE
Please remove fitforfun.de from blocklist(s)

### ISSUE THREAD

**Issue by thomasmerz** [Bon-Appetit/porn-domains#11]
This is not an "adult" (NSFW) or "porn" site:

> Fit for Fun war eine [Fitness](https://de.wikipedia.org/wiki/Fitness)-[Zeitschrift](https://de.wikipedia.org/wiki/Zeitschrift), die von 1994 bis 2021 monatlich erschien.

https://de.wikipedia.org/wiki/Fit_for_Fun

**Comment by CodeAlDente** [comment]
Thanks! Domain has been removed and added to whitelist.
